### ISSUE TITLE
world and body disturbance compensation

### ISSUE THREAD

**Issue by linuxdronethesis** [ctu-mrs/mrs_uav_controllers#2]
Good afternoon,
We are working on a project using the MRS flightstack and we would want to know what are exactly the world and body disturbance compensations ? Where do the disturbances come from and where can we remove it ?
Thank you in advance.

**Comment by klaxalk** [comment]
Hey, the math behind the disturbance estimators is described in here:
http://mrs.felk.cvut.cz/data/papers/mrs-platform.pdf

Thanks for showing an interest
Sincerely, Tomas

**Comment by linuxdronethesis** [comment]
Thank you for your answer ! It was very helpful. The world disturbance compensation compensates disturbance in the simulation environment like wind, correct ? But is it possible to remove those disturbances and where ?

**Comment by klaxalk** [comment]
Oh, ye, sorry, I misread your question. Yes, you are correct, the world
disturbances are the ones fixed to the world, e.g., wind, whereas the body
disturbances are fixed to the UAV body (typically a poor accelerometer
calibration can cause that, or air drag when flying with heading tangential
with the trajectory.

So in our simulation, there are usually no disturbances beyond the air
drag. So there is nothing to remove. Do you experience some significant
disturbances in normal flight? Btw, there is an rviz marker topic
control_manager/disturbances_markers, which shows the vectors of the
estimated disturbance (red = world, green = body, 1 m = 1 N).

Sincerely
Tomáš Báča
Czech Technical University in Prague
Department of Cybernetics
Multi-robot System Group
http://mrs.felk.cvut.cz/people/tomas-baca
tomas.baca@fel.cvut.cz



st 1. 7. 2020 v 14:28 odesílatel linuxdronethesis <notifications@github.com>
napsal:

**Comment by linuxdronethesis** [comment]
I do not experience significant disturbances but I experience static errors. To be clear I will explain what structure we use. We fixed the proportional and derivative gains of both the outer loop position control and the inner loop attitude control in the SO3 controller. We ask to track a fixed set point so there is no feedforward term. When removing the integral action (so the disturbances compensations and the modification of the mass) there is sometime a static error and sometimes not. It must come from the disturbances right ? But you said that there is no world disturbance except for air drag so it should not influence the static error. And are there body disturbances in a simulation ? I guess not. I will check the topic with the estimated disturbance ! Thank you

**Comment by linuxdronethesis** [comment]
For example with Kp = diag(10,10,10), Kd =diag(7,7,7), Kr = diag(14,14,14) and Kw = diag(0.7,0.7,0.7) in the formulas attached in the picture (computation of thrust force and torques to apply on the drone) we obtain the following result (in the third picture). The reference is in orange and the drone real position in blue. The used drone is the T650 in a gazebo simulation.
<img width="1435" alt="Capture d’écran 2020-07-02 à 16 47 37" src="https://user-images.githubusercontent.com/55850159/86375343-d648f800-bc85-11ea-92c3-2264cbb88524.png">
<img width="400" alt="Capture d’écran 2020-07-02 à 16 55 48" src="https://user-images.githubusercontent.com/55850159/86375347-d77a2500-bc85-11ea-9589-0aca11e17f3b.png">
<img width="200" alt="Capture d’écran 2020-07-02 à 16 55 52" src="https://user-images.githubusercontent.com/55850159/86375348-d812bb80-bc85-11ea-8674-d2601e28ae73.png">

**Comment by linuxdronethesis** [comment]
the x axis units are seconds

**Comment by linuxdronethesis** [comment]
And I forgot to tell but we also disabled the mpc tracker. The MPC tracker is no longer modifying the reference and the reference of the goto service is directly given to the SO3 controller.

**Comment by klaxalk** [comment]
Ye, so I can confirm that without the integrals, there is a steady-state
error, even in the simulator. I must admit, I rarely fly without the
integrals, since in real world, they are totally necessary. I guess that
there are effects that could cause this in simulation, e.g., the
accelerometer and gyroscope random walk, which are actually simulated
(check
https://github.com/ctu-mrs/mrs_simulation/blob/master/models/mrs_robots_description/urdf/t650.xacro).
There might be more. However, I don't see much of a purpose in your
actions. Why would you want to "disable" the disturbances, if they actually
model effects from the real world? Yes, in a perfect world, you would not
need an integrator in you controller, since the system itself contains >= 2
integrators, but you need one to counteract external disturbances and/or
input biases. And both occur on real hardware and are often prominent.
Moreover, I don't recommend disabling the mass estimator, since the
estimated mass is used by the SE3 to calculate the feed-forwards, as well
as the feedback.

Sincerely
Tomáš Báča
Czech Technical University in Prague
Department of Cybernetics
Multi-robot System Group
http://mrs.felk.cvut.cz/people/tomas-baca
tomas.baca@fel.cvut.cz



čt 2. 7. 2020 v 21:33 odesílatel linuxdronethesis <notifications@github.com>
napsal:

**Comment by linuxdronethesis** [comment]
Ok thank you for your detailed answer ! My goal was to make predictions on the future positions of the drone but since the disturbances are not taken into account in the predictions there is always a slight differences between the predictions and the drone real position. But now I know why :)
